### ISSUE TITLE
SimpleSearch on MODX 3.0.3 gives fatal error

### ISSUE THREAD

**Issue by lottaar** [modxcms/SimpleSearch#58]
After upgrading från MODX 2.X till MODX 3.0.3 and upgrading SimpleSearch to 3.0.0-alpha I can no longer save resources. Server log gives fatal error:

[Wed May 10 07:49:43.355135 2023] [proxy_fcgi:error] [pid 3614] [client 217.31.176.15:56176] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/vhosts/mysite.se/httpdocs/core/components/simplesearch/model/simplesearch/simplesearch.class.php' (include_path='.:/opt/plesk/php/8.2/share/pear') in /var/www/vhosts/mysite.se/httpdocs/core/cache/includes/elements/modx/revolution/modplugin/2.include.cache.php:37\nStack trace:\n#0 /var/www/vhosts/mysite.se/httpdocs/core/src/Revolution/modScript.php(88): include()\n#1 /var/www/vhosts/mysite.se/httpdocs/core/src/Revolution/modX.php(1710): MODX\\Revolution\\modScript->process()\n#2 /var/www/vhosts/mysite.se/httpdocs/core/src/Revolution/Processors/Resource/Update.php(891): MODX\\Revolution\\modX->invokeEvent()\n#3 /var/www/vhosts/mysite.se/httpdocs/core/src/Revolution/Processors/Resource/Update.php(677): MODX\\Revolution\\Processors\\Resource\\Update->fireDeleteEvent()\n#4 /var/www/vhosts/mysite.se/httpdocs/core/src/Revolution/Processors/Model/UpdateProcessor.php(92): MODX\\Revolution\\Processors\\Resource\\Update...', referer: https://mysite.se/manager/?a=resource/update&id=1

**Comment by lottaar** [comment]
Seems to have been related to #52 – solved by deleting plugin simplesearchindexer.
